# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1

pipelines:
  default:
  - parallel:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - echo "Running Java Project"
          - mvn -f "Central System/eapli-base/pom.xml" -B verify # -B batch mode makes Maven less verbose
          
#    - step:
#        script:
#          - echo "Running C Project"
#          - export DEBIAN_FRONTEND=noninteractive
#          - apt-get update && apt-get install make
#          - apt-get -y update && apt-get -y install gcc
#          - make -C MachineSimulator build

